# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- Developer

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud service connection'
    organization: 'aithuphanindra'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=aithuphanindra_Creditcard-Bill-Payment
      sonar.projectName=Creditcard-Bill-Payment

- task: Maven@4
  inputs:
    mavenPomFile: 'springcreditcard/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: Docker@2
  inputs:
    containerRegistry: 'docker serv conn'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'docker serv conn'
    repository: 'phani28 / demo1'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
