name: CI
# edit
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/aithuphanindra/sonarcloud_int
            azure-pipeline-name: 'Creditcard-Bill-Payment'
            azure-devops-token: ${{ secrets. }}
